### ISSUE TITLE
How to detect status of the buttons on P-Brick?

### ISSUE THREAD

**Issue by windoze** [pixix4/ev3dev-lang-rust#1]
I didn't find any useful info, did I miss anything?

**Comment by pixix4** [comment]
This is currently not possible. I plan to add this feature within the next week.

**Comment by windoze** [comment]
Thanks, this crate works pretty well, I successfully convert some existing Python programs into Rust, the overhead reduced to minimal.
And I hope you can add BrickPi support as well.

Thanks.

**Comment by pixix4** [comment]
The library does now support querying the state of the brick buttons (see [documentation](https://docs.rs/ev3dev-lang-rust/0.7.0/ev3dev_lang_rust/struct.Ev3Button.html)). 

The support for the BrickPi platform will take some time. Currently I don't own a BrickPi and so I can't do any tests.

**Comment by windoze** [comment]
Thanks a lot for the update, just verified and it worked like a charm.
