### ISSUE TITLE
Rc<RefCell<File>> cannot be sent between threads safely

### ISSUE THREAD

**Issue by calvinII** [pixix4/ev3dev-lang-rust#12]
Hi,
I'm trying to use threading in my robot software. But this library uses Rc<RefCell> which cannot be used over thread borders. I've read that it is possible to replace Rc with Arc which is accepted from the Rust compiler to be used in concurring threads. I'm completely new to Rust and I'm using my Mindstorms Robots to learn it ;/ So I'm not able to send in a good PR. 
So is this possible and a good Idea to replace this in this library?

At the moment I simply used a extra datastructure which uses Arc<Mutex<>> to exchange data between my threads. This datastructure is filled inside a thread from the corresponding sensor. So it is not really burning but annoying problem.

Example Error
`   Compiling run_on_console v0.1.0 (/build)
error[E0277]: `Rc<RefCell<File>>` cannot be sent between threads safely
   --> src/main.rs:56:5
    |
56  |     thread::spawn(move || {
    |     ^^^^^^^^^^^^^ `Rc<RefCell<File>>` cannot be sent between threads safely
    |
    = help: within `(String, Attribute)`, the trait `Send` is not implemented for `Rc<RefCell<File>>`
    = note: required because it appears within the type `Attribute`
    = note: required because it appears within the type `(String, Attribute)`
    = note: required because of the requirements on the impl of `Send` for `hashbrown::raw::RawTable<(String, Attribute)>`
    = note: required because it appears within the type `hashbrown::map::HashMap<String, Attribute, RandomState>`
    = note: required because it appears within the type `HashMap<String, Attribute>`
    = note: required because of the requirements on the impl of `Send` for `RefCell<HashMap<String, Attribute>>`
    = note: required because it appears within the type `Driver`
    = note: required because it appears within the type `UltrasonicSensor`
    = note: required because it appears within the type `[closure@src/main.rs:56:19: 62:6]``

Code which produces this Error:
`
fn main() {
....
    let ultrasonic = UltrasonicSensor::get(SensorPort::In4).unwrap();
    ultrasonic.set_mode_us_dc_cm().unwrap();
    let bar = Distance::new();
    let mut bar1 = bar.clone();
    thread::spawn(move || loop {
            bar1.update(ultrasonic.get_distance_centimeters().unwrap());
            thread::sleep(Duration::from_millis(10));
     });
...
`

**Comment by pixix4** [comment]
I have updated the mentioned code in version `0.10.0`. A short test script has compiled. However, I have not tested it extensively on the robot but it should work.
