### ISSUE TITLE
Add support for getting "raw" data

### ISSUE THREAD

**Issue by Eoghanmc22** [pixix4/ev3dev-lang-rust#14]
I could be wrong but currently I do not think it is possible to get the data described [here](https://github.com/ev3dev/ev3dev/wiki/Internals:-ev3dev-stretch) through this library. Main use case would be to get a more accurate wheel position.

**Comment by pixix4** [comment]
Cause this is an advanced feature I did not add an explicit wrapper. But I opened the `Attribute` module for arbitrary paths. With this module you can easily take advantage of the file handler caching and typed accessor methods. There are two usage options.

First you can use this module with an explicit path:
```rust
use ev3dev_lang_rust::Attribute;

let a = Attribute:: from_path("/sys/bus/iio/devices/iio:device1/in_count0_raw")?;
println!("{}", a.get::<i32>()?);
```

Second you can use a create method with a discriminator. This method helps to find the right subdirectory within a `root_path`:
```rust
use ev3dev_lang_rust::Attribute;

let a = Attribute::from_path_with_discriminator(
        "/sys/bus/iio/devices", // root_path
        "in_count0_raw",        // attribute_path
        "name",                 // discriminator_path
        "ev3-tacho"             // discriminator_value
)?;
println!("{}", a.get::<i32>()?);
```
More details for this variant can be found in the [docs](https://docs.rs/ev3dev-lang-rust/0.10.2/ev3dev_lang_rust/struct.Attribute.html#method.from_path_with_discriminator) and at the [example](https://github.com/pixix4/ev3dev-lang-rust/tree/master/examples/attributes).
