### ISSUE TITLE
way to reduce executable size

### ISSUE THREAD

**Issue by recursivetree** [pixix4/ev3dev-lang-rust#15]
When I compile a hello world example, the file size for the executable is about 3MB, compared to a few KB in C. This is a lot for only printing hello world, but the main problem is, that transferring it over with bluetooth takes about 30s. I assume that is because large portions of the standard library are included, but not required.

**Comment by pixix4** [comment]
I did some testing and found 2 easy ways to reduce the binary size for such an example by around 90% (to around 290 KB). You can try this with the new [template repository](https://github.com/pixix4/ev3dev-lang-rust-template/) or by manually applying the optimization as described in the readme.

**Comment by recursivetree** [comment]
thanks a lot, that helps!
