### ISSUE TITLE
Document code hidden behind `screen` feature

### ISSUE THREAD

**Issue by JohnTheCoolingFan** [pixix4/ev3dev-lang-rust#22]
This will show the API on docs.rs. Just use `#[cfg(any(feature = "screen", doc))]`.
Maybe I'll do a PR later

**Comment by mwobat** [comment]
Unfortunately, replacing all `#[cfg(feature = "screen")]` with `#[cfg(any(feature = "screen", doc))]` results in an error:
```
>cargo doc
...
error[E0463]: can't find crate for `framebuffer`
  --> src\lib.rs:37:1
   |
37 | extern crate framebuffer;
   | ^^^^^^^^^^^^^^^^^^^^^^^^^ can't find crate

error[E0463]: can't find crate for `image`
  --> src\lib.rs:40:1
   |
40 | extern crate image;
   | ^^^^^^^^^^^^^^^^^^^ can't find crate

For more information about this error, try `rustc --explain E0463`.
error: could not document `ev3dev-lang-rust`
```

Besides that, I think it would be important to show that the "screen" feature is needed. Example:
![image](https://github.com/pixix4/ev3dev-lang-rust/assets/98954380/6e0607c8-31b7-4357-99d4-59b6e358fd12)
However, the required "doc_cfg" feature is still experimental

**Comment by pixix4** [comment]
Thanks for the suggestions. This is now implemented. `docsrs` seems to use nightly rust by default. And with `#![cfg_attr(docsrs, feature(doc_cfg, doc_auto_cfg))]` the automatic feature documentation for `docsrs` can be enabled conditionally.
