### ISSUE TITLE
Cannot control EV3 motors

### ISSUE THREAD

**Issue by AuroraEchoes** [pixix4/ev3dev-lang-rust#25]
I have been unable to control motors on my EV3 running EV3Dev and this library. The program will continue through motor control instructions however it will not execute them. 

I have tested across multiple EV3s and sets of motors using both custom and example code provided. While this will not work, EV3Dev Python works on all of these systems – so it is a problem specific to this library.

I would appreciate any help. I'm not sure what additional information to include.

Thank you in advance!

**Comment by pixix4** [comment]
Do you have a repository with your code? And what ev3dev OS version are you using?

**Comment by pixix4** [comment]
I tested the example again and had a similar problem. The solution was to set an initial speed for the motors. The example is now updated and should work without any additional setup. Does this fix your problem too?

**Comment by AuroraEchoes** [comment]
Apologies for the slow response — GitHub didn't send me a notification and I forgot to check.

Yes this solves my problem. Thank you very much for your help.
