### ISSUE TITLE
error: linking with `cc` failed: exit code: 1

### ISSUE THREAD

**Issue by JanF-04** [pixix4/ev3dev-lang-rust#7]
When compiling I get the error `error: linking with 'cc' failed: exit code: 1`.
I know it is because the .cargo/config file is not set up properly. 
But there is only one .cargo/config file in my hole filesystem. Its path is "./home/<username>/.cargo/registry/src/github.com-1ecc6299db9ec823/ev3dev-lang-rust-0.9.5/.cargo/config". And I edited this one, so it shows:
`[target.armv5te-unknown-linux-gnueabi]
linker = "/usr/bin/arm-linux-gnueabi-gcc"`
I really don`t know which file to edit or how to compile the program.
Thanks for helping 👍

**Comment by pixix4** [comment]
The `config` file must be relative to your project directory. A minimal setup may look like this:

```
.cargo/config
src/main.rs
Cargo.toml
```

**Comment by JanF-04** [comment]
Thanks for helping,
worked for me :-D 👍
