### ISSUE TITLE
How can you use the derive macros from a crate that is not inside the library workspace?

### ISSUE THREAD

**Issue by Seppel3210** [pixix4/ev3dev-lang-rust#8]
I always get a `error: cannot find derive macro Device in this scope`

**Comment by pixix4** [comment]
I am not quite sure what you're trying to achieve. Usually you don't need to use the `Device` macro manually. If you really need to use it, try to import and allow macros from the derive crate explicitly.

```rust
// main.rs

#[macro_use]
extern crate ev3dev_lang_rust_derive;
```

**Comment by Seppel3210** [comment]
Yeah the thing was that I didn't clone the repository and when declaring `extern crate ev3dev_lang_rust_derive;` it says that it can't find the crate (obviously). My question was if I could use the macros without cloning the repository (sorry that I did't really make that clear).

**Comment by Seppel3210** [comment]
oh... I forgot to define the dependeny in `Cargo.toml`. I feel dumb
